Repository 2024-Winter-Bootcamp-Team-G/infra, pull requests merged in 2025-01, with the labels that each got.

#7 chore: prometheus, grafana, cadvisor 기본 환경 세팅
  .gitignore
  docker-compose.yml
  prometheus/prometheus.yml
Labels: 🧭 Chore

#9 chore: redis, postgres exporter 추가
  docker-compose.yml
  prometheus/prometheus.yml
Labels: 🧭 Chore

#22 [feat] github actions ci 연동
  .github/ci.yml
Labels: 🚀 Feat

#28 [fix] nginx.conf 수정
  nginx/nginx.conf
Labels: 🏷 Fix

#29 [feat] cd.yml 설정
  .github/workflows/cd.yml
Labels: 🚀 Feat

#31 [feat] grafana 비밀번호 설정
  docker-compose.monitoring.yml
Labels: 🚀 Feat
